import {
  CallIntelligence,
  FollowUpTask,
  FollowUpStatus,
  FollowUpType,
  FollowUpPriority,
  FollowUpChannel,
  ObjectionCategory,
  ObjectionDetail,
  AggregatedObjection,
  LeadTemperature,
  Lead,
  CallRecord,
  SophiaCallTurn,
} from '../types';
import { getStoredCallRecords, saveCallRecord } from './telephonyService';
import { addActivity } from './leadService';

const INTELLIGENCE_STORAGE_KEY = 'mca_call_intelligence_v1';
const FOLLOW_UPS_STORAGE_KEY = 'mca_follow_up_tasks_v1';

/**
 * Initial Seed Data for Phase 2F:
 * Realistic contractor calls with transcripts, objection details, and follow-up commitments.
 */
const SEED_CALL_INTELLIGENCE: CallIntelligence[] = [
  {
    intelligence_id: 'intel_seed_1',
    call_id: 'call_seed_apex_1',
    lead_id: 'lead-1',
    business_name: 'Apex Roofing & Restoration',
    contact_name: 'Marcus Vance',
    phone_number: '(503) 555-0142',
    summary:
      'Marcus acknowledged strong local referral business but expressed frustration with competitor rankings on Google Maps in Beaverton. Requested an email breakdown before scheduling a call.',
    sentiment: 'Positive',
    interest_level: 'Warm',
    engagement_score: 84,
    lead_temperature: 'Warm',
    confidence_score: 95,
    intents: ['Request Information', 'Request Audit', 'Email Follow-Up'],
    pain_points: [
      'Competitors dominating Beaverton Local 3-Pack',
      'High reliance on seasonal word of mouth',
      'Mobile website loads slowly on field smartphones',
    ],
    objections: [
      {
        id: 'obj_apex_1',
        category: 'Timing',
        prospect_statement: 'We have three large commercial roof tear-offs this week so I cannot do a live demo.',
        gemini_summary: 'Prospect is operating at field capacity this week and cannot take long meetings.',
        suggested_response_strategy:
          'Send a concise 2-minute async Loom audit comparing Beaverton Map Pack rankings without demanding a live meeting.',
      },
      {
        id: 'obj_apex_2',
        category: 'Already Has Provider',
        prospect_statement: 'My nephew built our site three years ago, but he does not really do marketing.',
        gemini_summary: 'Informal web management with zero active local search optimization.',
        suggested_response_strategy:
          'Reassure that existing site design can be kept while MCA supercharges GMB citations and Local Service Ads.',
      },
    ],
    business_needs: ['Local map visibility in Beaverton & Tigard', 'Steady commercial roofing quote requests'],
    current_marketing_situation: 'Word of mouth and static WordPress website with no GMB optimization.',
    existing_providers: 'Nephew / Informal',
    budget_signals: 'Comfortable with $2,000-$3,000/mo if 2-3 extra commercial roofs close.',
    timeline_signals: 'Wants to review material this week, follow up next Tuesday.',
    decision_maker_info: {
      name: 'Marcus Vance',
      role: 'Owner & General Contractor',
      availability: 'Tuesdays & Thursdays after 3 PM',
      decision_authority: 'Sole decision maker',
    },
    follow_up_commitments: {
      promise_by_agency: 'Email 2-minute Beaverton Local Pack competitor audit by end of day',
      prospect_request: 'Email video audit to marcus@apexroofing.com before scheduling next call',
      follow_up_type: 'Send Audit',
      recommended_date: new Date().toISOString().split('T')[0],
      timing_type: 'Exact Date',
      recommended_channel: 'Email',
      priority: 'High',
      reason: 'Marcus explicitly asked to review email audit today before speaking on Tuesday',
    },
    key_insights: [
      'Marcus values local Pacific Northwest knowledge over national marketing agencies.',
      'Average job value exceeds $8,500, creating high ROI potential.',
    ],
    next_best_action: {
      action: 'Send Personalized Audit',
      reason: 'Prospect expressed interest and requested information via email.',
      priority: 'High',
      suggested_channel: 'Email',
      suggested_timing: 'Today',
    },
    crm_notes: `CALL SUMMARY
Spoke with Marcus Vance at Apex Roofing & Restoration. Discussed Beaverton search presence and competitor displacement. Marcus confirmed high job margins but lacks map pack dominance.

PROSPECT INTEREST
Warm

PAIN POINTS DISCOVERED
* Competitors dominating Beaverton Local 3-Pack
* High reliance on seasonal word of mouth
* Mobile website slow loading

OBJECTIONS
* Timing: "We have three large commercial roof tear-offs this week" - Prospect in field
* Already Has Provider: "My nephew built our site three years ago" - Informal management

FOLLOW-UP COMMITMENT
Marketing Charm Agency committed to send 2-minute Beaverton competitor video audit via email today.

NEXT ACTION
Send personalized audit and schedule 10-minute review for next Tuesday at 3:30 PM.

(Generated by Sophia AI)`,
    generated_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    ai_provider: 'Google Gemini',
    ai_model: 'gemini-3.8-flash',
    raw_transcript: `[Sophia]: Hello Marcus, this is Sophia with Marketing Charm Agency here in Oregon. I noticed Apex Roofing has stellar 4.9-star ratings in Beaverton, but top map rankings are going to older contractors. Did I catch you with a moment?
[Marcus]: Hey Sophia. Yeah, I'm heading between jobs right now. We do good work, but honestly most of our work is word of mouth. We don't get many calls off Google.
[Sophia]: That's exactly why I reached out. Our audit showed three competitors in Beaverton capturing over 80% of local "roof replacement" searches because your Google profile is missing key local citations.
[Marcus]: Makes sense. My nephew built our site three years ago, but he does not really do marketing. We have three large commercial roof tear-offs this week so I cannot do a live demo.
[Sophia]: Totally understand Marcus, you guys are in the field. How about this: I won't take your time today. I will record a quick 2-minute video breakdown showing the exact search terms your competitors are taking, and email it directly to you. Would that be helpful?
[Marcus]: Yeah, shoot that over. If it looks solid, call me next Tuesday afternoon after 3 PM.
[Sophia]: Done! I'll email that over today and check in Tuesday afternoon. Have a safe day on the roofs!`,
    transcript_status: 'Available',
  },
  {
    intelligence_id: 'intel_seed_2',
    call_id: 'call_seed_pacific_2',
    lead_id: 'lead-2',
    business_name: 'Pacific Crest Plumbing',
    contact_name: 'Elena Rostova',
    phone_number: '(503) 555-0189',
    summary:
      'Elena was interested in capturing high-ticket repipe and commercial plumbing emergency jobs in Portland. She asked directly about retainer pricing and ROI.',
    sentiment: 'Positive',
    interest_level: 'Hot',
    engagement_score: 92,
    lead_temperature: 'Hot',
    confidence_score: 98,
    intents: ['Interested in Services', 'Price Concern', 'Request Proposal'],
    pain_points: [
      'Missing high-margin emergency plumbing search queries',
      'No tracking on inbound calls to measure conversion',
    ],
    objections: [
      {
        id: 'obj_pacific_1',
        category: 'Price',
        prospect_statement: 'We got burned by an agency charging $3,500 a month with zero guaranteed calls.',
        gemini_summary: 'Previous negative agency experience with unverified lead attribution.',
        suggested_response_strategy:
          'Provide clear call tracking dashboard, month-to-month terms, and CCB-compliant conversion funnels.',
      },
    ],
    business_needs: ['Emergency repipe calls', 'Attributable ROI dashboard'],
    current_marketing_situation: 'Paying for shared home advisor leads that convert poorly.',
    budget_signals: 'Budget available ($2,500-$4,000/mo) if leads are exclusive.',
    timeline_signals: 'Immediate need for Q3 pipeline growth.',
    decision_maker_info: {
      name: 'Elena Rostova',
      role: 'Managing Partner',
      availability: 'Mornings 9-11 AM',
      decision_authority: 'Co-owner with husband',
    },
    follow_up_commitments: {
      promise_by_agency: 'Send custom proposal with call attribution proof and case study by tomorrow',
      prospect_request: 'Send contract terms and sample dashboard before Thursday partner meeting',
      follow_up_type: 'Send Proposal',
      recommended_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
      timing_type: 'Exact Date',
      recommended_channel: 'Email',
      priority: 'Critical',
      reason: 'Elena reviewing with partner on Thursday morning',
    },
    key_insights: [
      'Elena is ready to switch from shared lead aggregators to direct agency inbound leads.',
      'High urgency; deal could close within 7 days.',
    ],
    next_best_action: {
      action: 'Send Proposal',
      reason: 'Elena requested terms and proposal for upcoming partner review.',
      priority: 'Critical',
      suggested_channel: 'Email',
      suggested_timing: 'Tomorrow Morning',
    },
    crm_notes: `CALL SUMMARY
High-intent consultation with Elena Rostova at Pacific Crest Plumbing. Focused on emergency repiping and commercial contracts in Portland.

PROSPECT INTEREST
Hot

PAIN POINTS DISCOVERED
* Missing high-margin emergency plumbing search queries
* Burned by shared lead aggregators

OBJECTIONS
* Price & Trust: "We got burned by an agency charging $3,500 a month with zero guaranteed calls"

FOLLOW-UP COMMITMENT
Agency promised to deliver exclusive inbound proposal and call tracking proof by tomorrow.

NEXT ACTION
Send tailored emergency plumbing proposal and follow up Thursday at 10 AM.

(Generated by Sophia AI)`,
    generated_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    ai_provider: 'Google Gemini',
    ai_model: 'gemini-3.8-flash',
    raw_transcript: `[Sophia]: Good morning Elena, this is Sophia with Marketing Charm Agency. How are you doing today?
[Elena]: Hi Sophia. Busy morning, but I have a couple of minutes. What can I do for you?
[Sophia]: I was reviewing Portland plumbing providers, and noticed Pacific Crest has stellar Google reviews, but when people search for emergency repipe services in SW Portland, your listing isn't appearing in the top 3.
[Elena]: Yeah, we get a lot of low-grade calls from HomeAdvisor, but not enough high-ticket repipes. But look, we got burned by an agency charging $3,500 a month with zero guaranteed calls last year.
[Sophia]: That is completely understandable Elena, and that agency failed you. We specialize strictly in local Pacific Northwest trade contractors. All our leads are 100% exclusive to you, with recorded call tracking so you hear every real prospect before paying.
[Elena]: That sounds a lot better than shared leads. Can you send over a proposal and sample tracking dashboard? I have a partner meeting on Thursday morning.
[Sophia]: Absolutely! I will have a custom proposal in your inbox by tomorrow morning so you have it ready for Thursday.`,
    transcript_status: 'Available',
  },
  {
    intelligence_id: 'intel_seed_3',
    call_id: 'call_seed_willamette_3',
    lead_id: 'lead-3',
    business_name: 'Willamette Valley Electric',
    contact_name: 'David Keller',
    phone_number: '(503) 555-0231',
    summary:
      'David was polite but stated they are currently booked out 6 weeks with panel upgrades. Interested in commercial EV charger installs for Q4.',
    sentiment: 'Neutral',
    interest_level: 'Warm',
    engagement_score: 68,
    lead_temperature: 'Warm',
    confidence_score: 90,
    intents: ['Request Callback', 'Future Need'],
    pain_points: ['Low margin residential jobs vs high margin commercial electrical & EV chargers'],
    objections: [
      {
        id: 'obj_willamette_1',
        category: 'Timing',
        prospect_statement: 'We are booked solid through next month, call me back in September.',
        gemini_summary: 'Near-term schedule saturation, but open to Q4 strategic planning.',
        suggested_response_strategy:
          'Set scheduled CRM follow-up for late summer with focus on commercial EV charger pipeline.',
      },
    ],
    business_needs: ['Commercial EV charging installations', 'Q4 schedule buffer'],
    current_marketing_situation: 'Referral only, zero active digital advertising.',
    budget_signals: 'Not an issue for commercial electrical projects.',
    timeline_signals: 'Timing Unknown / Late Q3.',
    decision_maker_info: {
      name: 'David Keller',
      role: 'Master Electrician & Owner',
      availability: 'Early mornings 7-8 AM',
      decision_authority: 'Sole decision maker',
    },
    follow_up_commitments: {
      promise_by_agency: 'Send seasonal electrical marketing guide and reconnect in 3 weeks',
      prospect_request: 'Check back when summer rush settles down',
      follow_up_type: 'Call Follow-Up',
      recommended_date: new Date(Date.now() + 86400000 * 21).toISOString().split('T')[0],
      timing_type: 'Relative',
      recommended_channel: 'Call',
      priority: 'Medium',
      reason: 'David requested reconnect after summer panel upgrade rush',
    },
    key_insights: ['High technical competence, receptive to data-driven commercial targeting.'],
    next_best_action: {
      action: 'Schedule Follow-Up Call',
      reason: 'Prospect requested check-in after summer capacity clears.',
      priority: 'Medium',
      suggested_channel: 'Call',
      suggested_timing: 'In 3 Weeks',
    },
    crm_notes: `CALL SUMMARY
Spoke with David Keller at Willamette Valley Electric. Currently booked out 6 weeks on residential panel work. Interested in commercial EV charger installations for autumn.

PROSPECT INTEREST
Warm

PAIN POINTS DISCOVERED
* Residential jobs taking crew time away from higher-margin commercial contracts

OBJECTIONS
* Timing: "We are booked solid through next month, call me back in September."

FOLLOW-UP COMMITMENT
Agency to send commercial EV charger case study and call back in 3 weeks.

NEXT ACTION
Log scheduled follow-up call task for late summer.

(Generated by Sophia AI)`,
    generated_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    ai_provider: 'Google Gemini',
    ai_model: 'gemini-3.8-flash',
    raw_transcript: `[Sophia]: Hi David, Sophia here with Marketing Charm Agency in Oregon. Hope your week is going well!
[David]: Pretty busy here Sophia. What's on your mind?
[Sophia]: I saw Willamette Valley Electric is doing great work across the valley. We've been helping electrical contractors secure high-margin commercial EV charger contracts.
[David]: Look, we are booked solid through next month with panel upgrades. It's our peak time right now.
[Sophia]: That's great to hear David! We don't want to overload you now. But when fall hits, would you like to have 2 or 3 high-margin commercial EV charger projects lined up?
[David]: That actually would be helpful for October and November. Can you give me a call back in about three weeks when things calm down?
[Sophia]: Absolutely David. I'll put a reminder on my calendar for 3 weeks from now. Have a great rest of the month!`,
    transcript_status: 'Available',
  },
];

/**
 * Initial Follow-Up Tasks seeded for Phase 2F
 */
const SEED_FOLLOW_UPS: FollowUpTask[] = [
  {
    follow_up_id: 'fu_task_1',
    lead_id: 'lead-1',
    lead_name: 'Apex Roofing & Restoration',
    contact_name: 'Marcus Vance',
    lead_phone: '(503) 555-0142',
    lead_email: 'marcus@apexroofing.com',
    source_call_id: 'call_seed_apex_1',
    type: 'Send Audit',
    channel: 'Email',
    reason: 'Prospect expressed interest and requested information via email during call with Sophia.',
    priority: 'High',
    recommended_date: new Date().toISOString().split('T')[0], // Today
    status: 'Pending',
    owner: 'Alex (Agency Rep)',
    ai_generated: true,
    ai_recommendation: 'Email 2-minute Beaverton Local Pack competitor audit by end of day.',
    context_notes: 'Marcus is on job sites today; send async Loom video so he can watch on mobile.',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    follow_up_id: 'fu_task_2',
    lead_id: 'lead-2',
    lead_name: 'Pacific Crest Plumbing',
    contact_name: 'Elena Rostova',
    lead_phone: '(503) 555-0189',
    lead_email: 'elena@pacificcrestplumbing.com',
    source_call_id: 'call_seed_pacific_2',
    type: 'Send Proposal',
    channel: 'Email',
    reason: 'Elena requested terms and proposal for upcoming partner review on Thursday morning.',
    priority: 'Critical',
    recommended_date: new Date(Date.now() + 86400000).toISOString().split('T')[0], // Tomorrow
    status: 'Scheduled',
    owner: 'Alex (Agency Rep)',
    ai_generated: true,
    ai_recommendation: 'Deliver emergency plumbing proposal with call tracking attribution guarantee.',
    context_notes: 'Include sample recorded lead dashboard and month-to-month terms to overcome past agency trauma.',
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    follow_up_id: 'fu_task_3',
    lead_id: 'lead-3',
    lead_name: 'Willamette Valley Electric',
    contact_name: 'David Keller',
    lead_phone: '(503) 555-0231',
    lead_email: 'david@wvelectric.com',
    source_call_id: 'call_seed_willamette_3',
    type: 'Call Follow-Up',
    channel: 'Call',
    reason: 'Prospect requested check-in after summer panel upgrade rush clears.',
    priority: 'Medium',
    recommended_date: new Date(Date.now() + 86400000 * 21).toISOString().split('T')[0],
    status: 'Scheduled',
    owner: 'Sophia (AI Sales Rep)',
    ai_generated: true,
    ai_recommendation: 'Check back when summer rush settles down with focus on commercial EV charger pipeline.',
    context_notes: 'Call between 7:00 AM and 8:00 AM before crew dispatches.',
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
  {
    follow_up_id: 'fu_task_4',
    lead_id: 'lead-4',
    lead_name: 'Cascade Heating & Air',
    contact_name: 'Travis Scott',
    lead_phone: '(503) 555-0312',
    lead_email: 'travis@cascadehvac.com',
    type: 'SMS Follow-Up',
    channel: 'SMS',
    reason: 'Follow up on AC tune-up campaign quote sent 48 hours ago.',
    priority: 'High',
    recommended_date: new Date(Date.now() - 86400000).toISOString().split('T')[0], // Overdue by 1 day
    status: 'Pending',
    owner: 'Alex (Agency Rep)',
    ai_generated: false,
    ai_recommendation: 'Send friendly SMS inquiry checking if Travis had time to review.',
    context_notes: 'Prefers text over phone calls during working hours.',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    follow_up_id: 'fu_task_5',
    lead_id: 'lead-5',
    lead_name: 'Summit Ridge Landscape',
    contact_name: 'Chloe Miller',
    lead_phone: '(503) 555-0455',
    type: 'AI Call Follow-Up',
    channel: 'AI Call',
    reason: 'Initial phone call went to voicemail; schedule automated follow-up dial.',
    priority: 'Low',
    recommended_date: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    status: 'Scheduled',
    owner: 'Sophia (AI Sales Rep)',
    ai_generated: true,
    ai_recommendation: 'Sophia outbound dial with customized commercial groundskeeping pitch.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

/**
 * Storage Accessors
 */
export function getAllCallIntelligence(): CallIntelligence[] {
  try {
    const raw = localStorage.getItem(INTELLIGENCE_STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(INTELLIGENCE_STORAGE_KEY, JSON.stringify(SEED_CALL_INTELLIGENCE));
      return SEED_CALL_INTELLIGENCE;
    }
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : SEED_CALL_INTELLIGENCE;
  } catch {
    return SEED_CALL_INTELLIGENCE;
  }
}

export function getCallIntelligence(callId: string): CallIntelligence | null {
  const all = getAllCallIntelligence();
  return all.find((item) => item.call_id === callId) || null;
}

export function saveCallIntelligence(intelligence: CallIntelligence): void {
  try {
    const all = getAllCallIntelligence();
    const existingIndex = all.findIndex((i) => i.intelligence_id === intelligence.intelligence_id || i.call_id === intelligence.call_id);
    if (existingIndex >= 0) {
      all[existingIndex] = { ...all[existingIndex], ...intelligence };
    } else {
      all.unshift(intelligence);
    }
    localStorage.setItem(INTELLIGENCE_STORAGE_KEY, JSON.stringify(all));

    // Also link back to CallRecord in telephony storage
    const callRecords = getStoredCallRecords();
    const targetCall = callRecords.find((c) => c.call_id === intelligence.call_id);
    if (targetCall) {
      targetCall.intelligence = intelligence;
      targetCall.engagement_score = intelligence.engagement_score;
      targetCall.lead_temperature = intelligence.lead_temperature;
      targetCall.sentiment = intelligence.sentiment === 'Mixed' ? 'Neutral' : intelligence.sentiment;
      targetCall.interest_level =
        intelligence.interest_level === 'Neutral'
          ? 'Warm'
          : intelligence.interest_level === 'Not Interested' || intelligence.interest_level === 'Do Not Contact'
          ? 'Cold'
          : intelligence.interest_level;
      targetCall.summary = intelligence.summary;
      targetCall.notes = intelligence.crm_notes;
      targetCall.recommended_next_action = intelligence.next_best_action.action;
      targetCall.key_insights = intelligence.key_insights;
      if (!targetCall.raw_transcript && intelligence.raw_transcript) {
        targetCall.raw_transcript = intelligence.raw_transcript;
      }
      saveCallRecord(targetCall);
    }
  } catch (e) {
    console.error('Failed to save call intelligence:', e);
  }
}

export function getFollowUpTasks(): FollowUpTask[] {
  try {
    const raw = localStorage.getItem(FOLLOW_UPS_STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(FOLLOW_UPS_STORAGE_KEY, JSON.stringify(SEED_FOLLOW_UPS));
      return SEED_FOLLOW_UPS;
    }
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : SEED_FOLLOW_UPS;
  } catch {
    return SEED_FOLLOW_UPS;
  }
}

export function getFollowUpTask(id: string): FollowUpTask | null {
  const all = getFollowUpTasks();
  return all.find((t) => t.follow_up_id === id) || null;
}

export function saveFollowUpTask(task: FollowUpTask): void {
  try {
    const all = getFollowUpTasks();
    const existingIndex = all.findIndex((t) => t.follow_up_id === task.follow_up_id);
    if (existingIndex >= 0) {
      all[existingIndex] = { ...all[existingIndex], ...task, updated_at: new Date().toISOString() };
    } else {
      all.unshift(task);
    }
    localStorage.setItem(FOLLOW_UPS_STORAGE_KEY, JSON.stringify(all));
  } catch (e) {
    console.error('Failed to save follow-up task:', e);
  }
}

export function updateFollowUpTask(id: string, updates: Partial<FollowUpTask>): FollowUpTask | null {
  const all = getFollowUpTasks();
  const index = all.findIndex((t) => t.follow_up_id === id);
  if (index >= 0) {
    all[index] = {
      ...all[index],
      ...updates,
      updated_at: new Date().toISOString(),
    };
    if (updates.status === 'Completed' && !all[index].completed_at) {
      all[index].completed_at = new Date().toISOString();
    }
    localStorage.setItem(FOLLOW_UPS_STORAGE_KEY, JSON.stringify(all));
    return all[index];
  }
  return null;
}

export function deleteFollowUpTask(id: string): void {
  try {
    const all = getFollowUpTasks().filter((t) => t.follow_up_id !== id);
    localStorage.setItem(FOLLOW_UPS_STORAGE_KEY, JSON.stringify(all));
  } catch (e) {
    console.error('Failed to delete follow-up task:', e);
  }
}

/**
 * Trigger Server-side AI / Gemini Analysis on Call Transcript
 */
export async function processCallTranscript(params: {
  callId: string;
  leadId?: string;
  transcript?: string;
  transcript_turns?: SophiaCallTurn[];
  lead?: Lead;
  callRecord?: CallRecord;
  duration?: number;
}): Promise<CallIntelligence> {
  const { callId, leadId, transcript, transcript_turns, lead, callRecord, duration } = params;

  try {
    const res = await fetch('/api/ai/process-transcript', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        transcript,
        transcript_turns,
        lead,
        callRecord,
        duration: duration || callRecord?.duration || 120,
      }),
    });

    if (res.ok) {
      const data = await res.json();
      if (data.intelligence) {
        const intelligence: CallIntelligence = {
          ...data.intelligence,
          call_id: callId,
          lead_id: leadId || lead?.lead_id || callRecord?.lead_id,
        };

        // Persist
        saveCallIntelligence(intelligence);

        // Auto-create a Follow-Up Task if a valid follow-up commitment was made
        if (
          intelligence.interest_level !== 'Do Not Contact' &&
          intelligence.interest_level !== 'Not Interested' &&
          intelligence.next_best_action
        ) {
          const newTask: FollowUpTask = {
            follow_up_id: `fu_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
            lead_id: leadId || lead?.lead_id || 'lead_general',
            lead_name: lead?.business_name || callRecord?.business_name || 'Prospect Business',
            contact_name: lead?.contact_name || callRecord?.contact_name,
            lead_phone: lead?.phone || callRecord?.phone_number,
            lead_email: lead?.email,
            source_call_id: callId,
            type:
              intelligence.follow_up_commitments?.follow_up_type === 'Send Audit'
                ? 'Send Audit'
                : intelligence.follow_up_commitments?.follow_up_type === 'Send Proposal'
                ? 'Send Proposal'
                : 'Call Follow-Up',
            channel:
              intelligence.next_best_action.suggested_channel === 'Email'
                ? 'Email'
                : intelligence.next_best_action.suggested_channel === 'SMS'
                ? 'SMS'
                : intelligence.next_best_action.suggested_channel === 'AI Call'
                ? 'AI Call'
                : 'Call',
            reason: intelligence.next_best_action.reason || 'Follow-up commitment from call discussion.',
            priority: intelligence.next_best_action.priority || 'High',
            recommended_date: new Date().toISOString().split('T')[0],
            status: 'Pending',
            owner: 'Alex (Agency Rep)',
            ai_generated: true,
            ai_recommendation: intelligence.next_best_action.action,
            context_notes: intelligence.summary,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          };
          saveFollowUpTask(newTask);
        }

        // Add activity event
        if (lead) {
          addActivity({
            id: `act-intel-${Date.now()}`,
            activity_id: `act-intel-${Date.now()}`,
            lead_id: lead.lead_id,
            lead_name: lead.business_name,
            timestamp: new Date().toISOString(),
            type: 'ai_analysis_generated',
            activity_type: 'ai_analysis_generated',
            channel: 'CALL',
            title: `Sophia Transcript Intelligence Generated (${intelligence.interest_level} • Score: ${intelligence.engagement_score})`,
            description: intelligence.summary,
            author: 'Sophia (AI Intelligence)',
            source: 'Post-Call Intelligence Engine',
            metadata: {
              intelligence_id: intelligence.intelligence_id,
              call_id: callId,
              engagement_score: intelligence.engagement_score,
              objections_count: intelligence.objections?.length || 0,
            },
          });
        }

        return intelligence;
      }
    }
  } catch (err) {
    console.warn('Backend process transcript failed, generating local fallback:', err);
  }

  // Local fallback intelligence
  const fallbackIntel: CallIntelligence = {
    intelligence_id: `intel_${Date.now()}`,
    call_id: callId,
    lead_id: leadId || lead?.lead_id,
    business_name: lead?.business_name || callRecord?.business_name || 'Prospect Business',
    contact_name: lead?.contact_name || callRecord?.contact_name || 'Owner',
    phone_number: callRecord?.phone_number || lead?.phone,
    summary: `Call completed with ${lead?.business_name || 'prospect'}. Discussed local marketing and website performance.`,
    sentiment: 'Neutral',
    interest_level: 'Warm',
    engagement_score: 72,
    lead_temperature: 'Warm',
    confidence_score: 85,
    intents: ['Request Information'],
    pain_points: ['Local search visibility', 'Competitor displacement'],
    objections: [
      {
        id: `obj_${Date.now()}`,
        category: 'Timing',
        prospect_statement: 'Call me back next week when things slow down.',
        gemini_summary: 'Prospect is focused on immediate operations.',
        suggested_response_strategy: 'Respect operational window and send asynchronous email summary.',
      },
    ],
    business_needs: ['Inbound contractor lead generation'],
    key_insights: ['Prospect open to asynchronous video audit.'],
    next_best_action: {
      action: 'Send Personalized Audit',
      reason: 'The prospect expressed interest and requested more information about website performance.',
      priority: 'High',
      suggested_channel: 'Email',
      suggested_timing: 'Today',
    },
    crm_notes: `CALL SUMMARY
Spoke with ${lead?.contact_name || 'Owner'} at ${lead?.business_name || 'Company'}. Reviewed current digital footprint in Oregon.

PROSPECT INTEREST
Warm

PAIN POINTS DISCOVERED
* Local search visibility
* Competitor displacement

OBJECTIONS
* Timing: Prospect requested follow-up next week.

FOLLOW-UP COMMITMENT
Agency to prepare 2-page digital audit.

NEXT ACTION
Send personalized audit via email.

(Generated by Sophia AI)`,
    generated_at: new Date().toISOString(),
    ai_provider: 'Google Gemini',
    ai_model: 'gemini-3.8-flash',
    raw_transcript: transcript || 'Transcript processed from call recording.',
    transcript_status: 'Available',
  };

  saveCallIntelligence(fallbackIntel);
  return fallbackIntel;
}

/**
 * Aggregated Objection Database Engine
 * Gathers, categorizes, and provides resolution strategies for every objection.
 */
export function getAggregatedObjections(filters?: {
  industry?: string;
  category?: string;
  minScore?: number;
}): AggregatedObjection[] {
  const allIntel = getAllCallIntelligence();

  const categories: ObjectionCategory[] = [
    'Price',
    'Timing',
    'Already Has Provider',
    'Too Busy',
    'Trust',
    'No Budget',
    'Not Interested',
    'Bad Previous Experience',
    'No Need',
    'Decision Maker Unavailable',
    'Other',
  ];

  const categoryMap: Record<
    ObjectionCategory,
    {
      count: number;
      industries: Set<string>;
      statements: string[];
      leads: Set<string>;
      lastDetected: string;
    }
  > = categories.reduce((acc, cat) => {
    acc[cat] = {
      count: 0,
      industries: new Set(),
      statements: [],
      leads: new Set(),
      lastDetected: '',
    };
    return acc;
  }, {} as any);

  let totalObjections = 0;

  allIntel.forEach((intel) => {
    (intel.objections || []).forEach((obj) => {
      const cat = obj.category || 'Other';
      if (!categoryMap[cat]) return;

      categoryMap[cat].count += 1;
      totalObjections += 1;
      if (intel.business_name) categoryMap[cat].industries.add(intel.business_name);
      if (intel.lead_id) categoryMap[cat].leads.add(intel.lead_id);
      if (obj.prospect_statement && !categoryMap[cat].statements.includes(obj.prospect_statement)) {
        categoryMap[cat].statements.push(obj.prospect_statement);
      }
      if (!categoryMap[cat].lastDetected || new Date(intel.generated_at) > new Date(categoryMap[cat].lastDetected)) {
        categoryMap[cat].lastDetected = intel.generated_at;
      }
    });
  });

  const responseStrategies: Record<ObjectionCategory, string> = {
    Price:
      'Reframe fee against single high-ticket job margin ($8,000+). Highlight 90-day ROI attribution and transparent lead tracking.',
    Timing:
      'Pivot immediately from synchronous live meetings to a 2-minute asynchronous video audit they can watch on their smartphone in the field.',
    'Already Has Provider':
      'Compliment existing relationship. Clarify that MCA does not replace web designers; we execute trade-specific local Map Pack rankings and citation architecture.',
    'Too Busy':
      'Validate seasonal peak. Explain that search ranking equity takes 30-60 days to mature, so starting now ensures high-margin bookings when slow season arrives.',
    Trust:
      'Share CCB verification data, Oregon-specific contractor case studies, and month-to-month terms with zero long-term lock-in.',
    'No Budget':
      'Offer localized Starter Verification package or contingency-backed local service ad launch.',
    'Not Interested':
      'Respectfully disengage, confirm if they wish to receive annual Oregon CCB regulatory updates, or mark Do Not Contact.',
    'Bad Previous Experience':
      'Differentiate by proving exclusive leads (never shared with 4 other contractors like HomeAdvisor) and providing recorded call access.',
    'No Need':
      'Highlight commercial or high-ticket service gap (e.g. panel upgrades vs outlets) where competitors are monopolizing search volume.',
    'Decision Maker Unavailable':
      'Confirm direct mobile number and best morning window (typically 7:00-8:00 AM before crews deploy) for a 3-minute executive briefing.',
    Other:
      'Ask clarifying open-ended discovery questions to uncover the underlying commercial hesitation.',
  };

  const results: AggregatedObjection[] = categories
    .map((cat) => {
      const data = categoryMap[cat];
      return {
        category: cat,
        count: data.count,
        percentage: totalObjections > 0 ? Math.round((data.count / totalObjections) * 100) : 0,
        top_industries: Array.from(data.industries).slice(0, 3),
        sample_statements: data.statements.slice(0, 3),
        recommended_response: responseStrategies[cat],
        last_detected: data.lastDetected || new Date().toISOString(),
        leads_affected: data.leads.size,
      };
    })
    .filter((o) => (filters?.category ? o.category === filters.category : true))
    .sort((a, b) => b.count - a.count);

  return results;
}

/**
 * Contextual Follow-Up Draft Generators
 * Pre-fills Email / SMS / Call strategy with conversation memory from transcripts.
 */
export function generateContextualEmailDraft(
  lead: Lead,
  followUp?: FollowUpTask,
  intel?: CallIntelligence
): { subject: string; body: string } {
  const business = lead.business_name || 'your business';
  const contact = lead.contact_name ? lead.contact_name.split(' ')[0] : 'there';
  const commitment = intel?.follow_up_commitments?.promise_by_agency || followUp?.ai_recommendation;

  const subject = `Following up on our call: ${business} Oregon local audit`;

  const body = `Hi ${contact},

It was great connecting on the phone earlier. As promised, I put together the digital analysis for ${business} focusing on your local Google search rankings and competitor positioning in ${lead.city || 'Oregon'}.

${commitment ? `Key takeaway we discussed: ${commitment}.\n\n` : ''}Here is the breakdown of what we found:
• Top 3 Google Map Pack competitor visibility in your area
• Opportunities to capture higher-margin service requests without relying solely on word of mouth
• Recommended immediate optimizations for your mobile visitors

Take a quick look at your convenience, and let me know if Thursday afternoon at 3:30 PM works for a brief 10-minute walk-through.

Best regards,

Alex & Sophia
Marketing Charm Agency`;

  return { subject, body };
}

export function generateContextualSMSDraft(
  lead: Lead,
  followUp?: FollowUpTask,
  intel?: CallIntelligence
): string {
  const contact = lead.contact_name ? lead.contact_name.split(' ')[0] : '';
  const prefix = contact ? `Hi ${contact}, ` : 'Hi, ';
  const commitment = intel?.follow_up_commitments?.promise_by_agency || 'the local audit';

  return `${prefix}Alex from Marketing Charm Agency following up on our call regarding ${lead.business_name}. I just sent over ${commitment} to your email. Let me know when you have 5 minutes to review!`;
}
